// Generated by gencpp from file rfans_driver/RfansPacket.msg
// DO NOT EDIT!


#ifndef RFANS_DRIVER_MESSAGE_RFANSPACKET_H
#define RFANS_DRIVER_MESSAGE_RFANSPACKET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rfans_driver
{
template <class ContainerAllocator>
struct RfansPacket_
{
  typedef RfansPacket_<ContainerAllocator> Type;

  RfansPacket_()
    : stamp()
    , udpCount(0)
    , udpSize(0)
    , data()  {
    }
  RfansPacket_(const ContainerAllocator& _alloc)
    : stamp()
    , udpCount(0)
    , udpSize(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint32_t _udpCount_type;
  _udpCount_type udpCount;

   typedef uint32_t _udpSize_type;
  _udpSize_type udpSize;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rfans_driver::RfansPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfans_driver::RfansPacket_<ContainerAllocator> const> ConstPtr;

}; // struct RfansPacket_

typedef ::rfans_driver::RfansPacket_<std::allocator<void> > RfansPacket;

typedef boost::shared_ptr< ::rfans_driver::RfansPacket > RfansPacketPtr;
typedef boost::shared_ptr< ::rfans_driver::RfansPacket const> RfansPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfans_driver::RfansPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfans_driver::RfansPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rfans_driver::RfansPacket_<ContainerAllocator1> & lhs, const ::rfans_driver::RfansPacket_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.udpCount == rhs.udpCount &&
    lhs.udpSize == rhs.udpSize &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rfans_driver::RfansPacket_<ContainerAllocator1> & lhs, const ::rfans_driver::RfansPacket_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rfans_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rfans_driver::RfansPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfans_driver::RfansPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfans_driver::RfansPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfans_driver::RfansPacket_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfans_driver::RfansPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfans_driver::RfansPacket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfans_driver::RfansPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "286ca481769f47d50a9a59b4e0d0d156";
  }

  static const char* value(const ::rfans_driver::RfansPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x286ca481769f47d5ULL;
  static const uint64_t static_value2 = 0x0a9a59b4e0d0d156ULL;
};

template<class ContainerAllocator>
struct DataType< ::rfans_driver::RfansPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfans_driver/RfansPacket";
  }

  static const char* value(const ::rfans_driver::RfansPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfans_driver::RfansPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Raw Rfans LIDAR packet.\n"
"#Header        header         # standard ROS message header\n"
"time stamp              # packet timestamp\n"
"uint32 udpCount          # packet number\n"
"uint32 udpSize\n"
"uint8[] data      # packet contents 600 Block\n"
;
  }

  static const char* value(const ::rfans_driver::RfansPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfans_driver::RfansPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.udpCount);
      stream.next(m.udpSize);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RfansPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfans_driver::RfansPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfans_driver::RfansPacket_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "udpCount: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.udpCount);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "udpSize: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.udpSize);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFANS_DRIVER_MESSAGE_RFANSPACKET_H
